Add react-native-caching-android

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -931,6 +931,52 @@ workflows:
             npx react-native build-ios
         title: npx react-native build-ios
     - save-cocoapods-cache@1: {}
+  react-native-caching-android:
+    steps:
+    - activate-ssh-key@4: {}
+    - git::https://github.com/bitrise-steplib/bitrise-step-simple-git-clone.git:
+        inputs:
+        - repository_url: git@github.com:inaturalist/SeekReactNative.git
+        - clone_into_dir: ./_tmp
+        - commit: 036d8a6c3eb6ea15482e5afe6b7212028088cd21
+    - change-workdir@1:
+        inputs:
+        - path: ./_tmp
+    - script@1:
+        inputs:
+        - content: |-
+            #!/usr/bin/env bash
+            # fail if any commands fails
+            set -eo pipefail
+
+            npm install
+        title: npm install
+    - script@1:
+        inputs:
+        - content: |-
+            #!/usr/bin/env bash
+            set -eo pipefail
+
+            mv ./android/app/src/main/res/values/config.example.xml ./android/app/src/main/res/values/config.xml
+            mv config.example.js config.js
+        title: Create configs
+    - script@1:
+        inputs:
+        - content: |-
+            #!/usr/bin/env bash
+            set -eo pipefail
+
+            npm run add-example-model
+        title: Add example models
+    - activate-build-cache-for-gradle@2: {}
+    - script@1:
+        inputs:
+        - content: |-
+            #!/usr/bin/env bash
+            set -eo pipefail
+
+            npx react-native build-android
+        title: npx react-native build-ios
 
 step_bundles:
   generate_gradle_verification_reference:
