React + ccache

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -1156,6 +1156,178 @@ workflows:
 
             npm run build:android
         title: npm run build:android
+  rn-cache-seek-android-ccache:
+    meta:
+      bitrise.io:
+        machine_type_id: g2.mac.medium
+        stack: osx-xcode-edge
+    steps:
+    - activate-ssh-key@4: {}
+    - git::https://github.com/bitrise-steplib/bitrise-step-simple-git-clone.git:
+        inputs:
+        - repository_url: git@github.com:inaturalist/SeekReactNative.git
+        - clone_into_dir: ./_tmp
+        - commit: 036d8a6c3eb6ea15482e5afe6b7212028088cd21
+    - change-workdir@1:
+        inputs:
+        - path: ./_tmp
+    - script@1:
+        inputs:
+        - content: |-
+            #!/usr/bin/env bash
+            # fail if any commands fails
+            set -eo pipefail
+
+            npm install
+        title: npm install
+    - script@1:
+        inputs:
+        - content: |-
+            #!/usr/bin/env bash
+            set -eo pipefail
+
+            cat > ./android/app/src/main/res/values/config.xml <<'EOF'
+            <?xml version="1.0" encoding="utf-8"?>
+            <!-- copy this file to config.xml and uncomment / fill in the values specific to your project -->
+            <resources>
+                <!-- https://developers.google.com/maps/documentation/android/ -->
+                <string name="gmaps_api_key">xxx</string>
+            </resources>
+            EOF
+
+            mv config.example.js config.js
+        title: Create configs
+    - script@1:
+        inputs:
+        - content: |-
+            #!/usr/bin/env bash
+            set -eo pipefail
+
+            npm run add-example-model
+        title: Add example models
+    - script@1:
+        inputs:
+        - content: |-
+            #!/usr/bin/env bash
+            set -eo pipefail
+
+            npx react-native build-android
+        title: no cache
+    - brew-install@1:
+        inputs:
+        - packages: ccache
+        title: Brew install ccache
+    - activate-build-cache-for-gradle@2: {}
+    - script@1:
+        inputs:
+        - content: |-
+            #!/usr/bin/env bash
+            set -eo pipefail
+
+            npx react-native build-android
+        title: gradle build cache only
+    - script@1:
+        inputs:
+        - content: |-
+            #!/usr/bin/env bash
+            # fail if any commands fails
+            set -eo pipefail
+
+            ccache -s
+            ccache -z
+        title: ccache stats
+    - script@1:
+        inputs:
+        - content: |-
+            #!/usr/bin/env bash
+            set -eo pipefail
+
+            npx react-native build-android
+        title: gradle build cache with ccache
+    - script@1:
+        inputs:
+        - content: |-
+            #!/usr/bin/env bash
+            # fail if any commands fails
+            set -eo pipefail
+
+            ccache -s
+            ccache -z
+        title: ccache stats
+  rn-cache-notesnook-android-ccache:
+    meta:
+      bitrise.io:
+        machine_type_id: g2.mac.medium
+        stack: osx-xcode-edge
+    tools:
+      ruby: 3.3:installed
+      nodejs: 24:installed
+    steps:
+    - activate-ssh-key@4: {}
+    - git::https://github.com/bitrise-steplib/bitrise-step-simple-git-clone.git:
+        inputs:
+        - repository_url: git@github.com:streetwriters/notesnook.git
+        - clone_into_dir: ./_tmp
+        - commit: e635ace33876f555ea5f1397a96073853e64a304
+    - change-workdir@1:
+        inputs:
+        - path: ./_tmp
+    - script@1:
+        inputs:
+        - content: |-
+            #!/usr/bin/env bash
+            set -eo pipefail
+
+            sed -i.bak 's/YOUR_APP/Notesnook/g' ./apps/mobile/.detoxrc.js
+            npm ci
+        title: npm install
+    - script@1:
+        inputs:
+        - content: |-
+            #!/usr/bin/env bash
+            set -eo pipefail
+
+            npm run build:android
+        title: build w/o cache
+    - brew-install@1:
+        inputs:
+        - packages: ccache
+        title: Brew install ccache
+    - activate-build-cache-for-gradle@2: {}
+    - script@1:
+        inputs:
+        - content: |-
+            #!/usr/bin/env bash
+            set -eo pipefail
+
+            npm run build:android
+        title: build with gradle build cache
+    - script@1:
+        inputs:
+        - content: |-
+            #!/usr/bin/env bash
+            set -eo pipefail
+
+            ccache -s
+            ccache -z
+        title: ccache stats
+    - script@1:
+        inputs:
+        - content: |-
+            #!/usr/bin/env bash
+            set -eo pipefail
+
+            npm run build:android
+        title: build with gradle build cache
+    - script@1:
+        inputs:
+        - content: |-
+            #!/usr/bin/env bash
+            set -eo pipefail
+
+            ccache -s
+            ccache -z
+        title: ccache stats
 step_bundles:
   generate_gradle_verification_reference:
     steps:
