feat: ACI-3863 Assert invocations from API too (#151)

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -10,6 +10,10 @@ app:
   envs:
   - PANDOC_VERSION: "3.6.2"
   - MAVEN_VERSION: "3.9.9"
+    # These are needed for the E2E test assertion logic
+  - WORKSPACE_SLUG: 322a005426441b60
+  - MONOLITH_API_PAT: $BITRISE_BUILD_CACHE_AUTH_TOKEN
+  - TRIGGERED_BUILD_SLUG: $BITRISE_BUILD_SLUG
 
 workflows:
   release:
@@ -247,6 +251,10 @@ workflows:
     - BRANCH: develop
     steps:
     - bundle::feature-e2e-setup: {}
+    - apt-get-install:
+        inputs:
+          - packages: 'bc'
+          - upgrade: "no"
     - script:
         title: Enable build cache
         inputs:
@@ -274,6 +282,27 @@ workflows:
               '\[Bitrise Build Cache\].*🤖 Bitrise remote cache enabled' \
               '\[Bitrise Build Cache\].*Request metadata invocationId' \
               '\[Bitrise Analytics\].*🤖 Bitrise analytics enabled for tasks.*Invocation ID: [0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}'
+            
+            source ../_e2e/scripts/extract_invocation_id.sh
+            
+            invocation_id=$(extract_invocation_id_gradle "$BITRISE_DEPLOY_DIR/logs.txt")
+            if [[ -z "$invocation_id" ]]; then
+              fatal "Invocation ID not found in logs"
+            fi
+
+            echo "Found Invocation ID: $invocation_id"
+            envman add --key INVOCATION_ID --value "$invocation_id"
+    - script:
+        title: Assert invocation from API
+        inputs:
+          - content: |-
+              source ../_e2e/scripts/assert_invocations.sh
+
+              assert_bitrise_invocation_in_list "$INVOCATION_ID" "gradle"
+              assert_bitrise_invocation_detail "$INVOCATION_ID" "gradle"
+              assert_invocation_tasks_gradle "$INVOCATION_ID"
+              assert_build_performance "$INVOCATION_ID"
+              assert_invocation_in_build_performance "$INVOCATION_ID" "gradle"
     - deploy-to-bitrise-io@2: {}
 
   feature-e2e-gradle-bitwarden:
@@ -282,6 +311,10 @@ workflows:
     - COMMIT: 2c71ab7d27d7f976766adee7bfd1828d5eda0850
     steps:
     - bundle::feature-e2e-setup: {}
+    - apt-get-install:
+        inputs:
+          - packages: 'bc'
+          - upgrade: "no"
     - script:
         title: Enable build cache
         inputs:
@@ -337,6 +370,27 @@ workflows:
               '\[Bitrise Build Cache\].*🤖 Bitrise remote cache enabled' \
               '\[Bitrise Build Cache\].*Request metadata invocationId' \
               '\[Bitrise Analytics\].*🤖 Bitrise analytics enabled for tasks.*Invocation ID: [0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}'
+            
+            source ../_e2e/scripts/extract_invocation_id.sh
+            
+            invocation_id=$(extract_invocation_id_gradle "$BITRISE_DEPLOY_DIR/logs.txt")
+            if [[ -z "$invocation_id" ]]; then
+              fatal "Invocation ID not found in logs"
+            fi
+
+            echo "Found Invocation ID: $invocation_id"
+            envman add --key INVOCATION_ID --value "$invocation_id"
+    - script:
+        title: Assert invocation from API
+        inputs:
+          - content: |-
+              source ../_e2e/scripts/assert_invocations.sh
+
+              assert_bitrise_invocation_in_list "$INVOCATION_ID" "gradle"
+              assert_bitrise_invocation_detail "$INVOCATION_ID" "gradle"
+              assert_invocation_tasks_gradle "$INVOCATION_ID"
+              assert_build_performance "$INVOCATION_ID"
+              assert_invocation_in_build_performance "$INVOCATION_ID" "gradle"
     - deploy-to-bitrise-io@2: {}
   feature-e2e-bazel-bitrisedc-no-rbe:
     meta:
@@ -348,6 +402,10 @@ workflows:
     - BRANCH: master
     steps:
     - bundle::feature-e2e-setup: {}
+    - apt-get-install:
+        inputs:
+          - packages: 'bc'
+          - upgrade: "no"
     - script@1:
         inputs:
         - content: |
@@ -380,9 +438,122 @@ workflows:
               '--bes_header=x-os=Linux' \
               '--bes_header=x-cpu-cores=[0-9]+' \
               '--bes_header=x-mem-size=[0-9]+' \
+              '--bes_header=x-ci-provider=bitrise' \
+              "--bes_header=x-app-id=$BITRISE_APP_SLUG" \
               '--bes_header=x-locale=\w+' \
-              '--bes_header=x-default-charset=\w+' \
+              '--bes_header=x-default-charset=\w+'
+            
+              source ../_e2e/scripts/extract_invocation_id.sh
+            
+              invocation_id=$(extract_invocation_id_bazel "$BITRISE_DEPLOY_DIR/logs.txt")
+              if [[ -z "$invocation_id" ]]; then
+                fatal "Invocation ID not found in logs"
+              fi
+
+              echo "Found Invocation ID: $invocation_id"
+              envman add --key INVOCATION_ID --value "$invocation_id"
+    - script:
+        title: Assert invocation from API
+        inputs:
+          - content: |-
+              source ../_e2e/scripts/assert_invocations.sh
+              
+              assert_bitrise_invocation_in_list "$INVOCATION_ID" "bazel"
+              assert_bitrise_invocation_detail "$INVOCATION_ID" "bazel"
+              assert_invocation_targets_bazel "$INVOCATION_ID"
+              assert_build_performance "$INVOCATION_ID"
+              assert_invocation_in_build_performance "$INVOCATION_ID" "bazel"
     - deploy-to-bitrise-io@2: {}
+
+  feature-e2e-bazel-public-no-rbe:
+    meta:
+      bitrise.io:
+        stack: linux-docker-android-22.04
+        machine_type_id: g2.linux.medium
+    envs:
+      - TEST_APP_URL: git@github.com:bitrise-io/bazel.git
+      - BRANCH: master
+    steps:
+      - bundle::feature-e2e-setup: { }
+      - apt-get-install:
+          inputs:
+            - packages: 'bc dnsutils iputils-ping'
+            - upgrade: "no"
+      - script:
+          title: Enable build cache
+          inputs:
+            - content: |-
+                #!/bin/bash
+                set -exo pipefail
+                                
+                echo "Bitrise step ID: $BITRISE_STEP_EXECUTION_ID"
+                ../bitrise-build-cache-cli activate bazel -d --cache --cache-push --bes --timestamps
+      - script:
+          title: Build and capture logs using Docker
+          inputs:
+            - content: |-
+                #!/bin/bash
+                set -exo pipefail
+                
+                mkdir -p ../_dockerroot
+                cp -r $HOME/.bazelrc ../_dockerroot/.bazelrc
+                                
+                sudo docker run --rm \
+                  -w "/workspace" \
+                  -e "BITRISE_APP_SLUG=$BITRISE_APP_SLUG" \
+                  -e "BITRISE_BUILD_SLUG=$BITRISE_BUILD_SLUG" \
+                  -e "BITRISE_STEP_EXECUTION_ID=$BITRISE_STEP_EXECUTION_ID" \
+                  -e "BITRISE_TRIGGERED_WORKFLOW_TITLE=$BITRISE_TRIGGERED_WORKFLOW_TITLE" \
+                  -e "GIT_REPOSITORY_UR=$GIT_REPOSITORY_URL" \
+                  -e "BITRISE_GIT_COMMIT=$BITRISE_GIT_COMMIT" \
+                  --mount "type=bind,source=$PWD,target=/workspace" \
+                  --mount "type=bind,source=$(readlink -f ../_dockerroot)/.bazelrc,target=/root/.bazelrc,ro" \
+                  --mount "type=bind,source=$BITRISE_DEPLOY_DIR,target=/bitrise-deploy" \
+                  ubuntu:22.04 \
+                  sh -c "apt-get update && apt-get install -y curl build-essential xz-utils && \
+                    curl -Lo bazelisk https://github.com/bazelbuild/bazelisk/releases/latest/download/bazelisk-linux-amd64 && \
+                    chmod +x bazelisk && \
+                    ./bazelisk build //src:bazel-dev --announce_rc --copt='-w' 2>&1 | tee /bitrise-deploy/logs.txt"
+                
+      - script:
+          title: Check for cache invocations
+          inputs:
+            - content: |-
+                #!/bin/bash
+                set -exo pipefail
+                
+                ../scripts/check_pattern.sh "$BITRISE_DEPLOY_DIR/logs.txt" \
+                  '--remote_cache=grpcs:\/\/bitrise-accelerate\.services\.bitrise\.io' \
+                  'Invocation ID: ' \
+                  '--bes_header=x-os=Linux' \
+                  '--bes_header=x-cpu-cores=[0-9]+' \
+                  '--bes_header=x-mem-size=[0-9]+' \
+                  '--bes_header=x-ci-provider=bitrise' \
+                  "--bes_header=x-app-id=$BITRISE_APP_SLUG" \
+                  '--bes_header=x-locale=\w+' \
+                  '--bes_header=x-default-charset=\w+'
+                
+                  source ../_e2e/scripts/extract_invocation_id.sh
+                
+                  invocation_id=$(extract_invocation_id_bazel "$BITRISE_DEPLOY_DIR/logs.txt")
+                  if [[ -z "$invocation_id" ]]; then
+                    fatal "Invocation ID not found in logs"
+                  fi
+                
+                  echo "Found Invocation ID: $invocation_id"
+                  envman add --key INVOCATION_ID --value "$invocation_id"
+      - script:
+          title: Assert invocation from API
+          inputs:
+            - content: |-
+                source ../_e2e/scripts/assert_invocations.sh
+                
+                assert_bitrise_invocation_in_list "$INVOCATION_ID" "bazel"
+                assert_bitrise_invocation_detail "$INVOCATION_ID" "bazel"
+                assert_invocation_targets_bazel "$INVOCATION_ID"
+                assert_build_performance "$INVOCATION_ID"
+                assert_invocation_in_build_performance "$INVOCATION_ID" "bazel"
+      - deploy-to-bitrise-io@2: { }
 
   gradle-configuration-e2e-osx:
     meta:
@@ -715,7 +886,24 @@ step_bundles:
       - activate-ssh-key:
           run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
       - script:
-          title: Delete _tmp dir
+          title: Clone e2e testing repo with deploy key
+          inputs:
+            - content: |-
+                #!/bin/bash
+                set -ex
+                
+                mkdir -p ~/.ssh
+                echo "$SSH_DEPLOY_KEY_E2E_TESTING" > ~/.ssh/github_deploy_build_cache_e2e_testing
+                chmod 600 ~/.ssh/github_deploy_build_cache_e2e_testing
+                
+                ssh-add ~/.ssh/github_deploy_build_cache_e2e_testing
+                
+                mkdir -p ./_e2e
+                GIT_SSH_COMMAND='ssh -i ~/.ssh/github_deploy_build_cache_e2e_testing -o IdentitiesOnly=yes' git clone git@github.com:bitrise-io/build-cache-e2e-testing.git ./_e2e
+                
+                ls -la ./_e2e
+      - script:
+          title: Delete _tmp dirs
           inputs:
             - content: rm -rf _tmp
       - git::https://github.com/bitrise-steplib/bitrise-step-simple-git-clone.git:
@@ -741,6 +929,7 @@ pipelines:
     workflows:
       test: {}
       feature-e2e-bazel-bitrisedc-no-rbe: {}
+      feature-e2e-bazel-public-no-rbe: {}
       feature-e2e-gradle-duckduck: {}
       feature-e2e-gradle-bitwarden: {}
       gradle-configuration-e2e-osx: {}
